name: maths_website
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image: ^4.0.17
  carousel_slider: ^4.0.0
  chewie: ^1.0.0
  video_player: ^2.1.0
  url_launcher: ^6.1.11
  flutter_charts: ^0.5.1
  google_fonts: ^4.0.3
  animated_text_kit: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

assets:
  -assets/Vikram.jpg
  -assets/manipur_districts/
